language: ruby
script:
  - bundle exec rubocop
  - bundle exec rspec

matrix:
  include:
    - rvm: ruby-head
    - rvm: 2.3.1
    - rvm: 2.2.5

    - rvm: 2.2.2
      gemfile: Gemfile.lte-2.2.2
    - rvm: 2.1.0
      gemfile: Gemfile.lte-2.2.2
    - rvm: 2.0.0
      gemfile: Gemfile.lte-2.2.2

    - rvm: jruby-head
    - rvm: jruby-9.1.0.0
    - rvm: jruby-9.0.0.0
      gemfile: Gemfile.lte-2.2.2

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  on_success: change
  on_failure: change
