sudo: false
language: ruby

script: "bundle exec rspec"

rvm:
  - ruby-head
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - 2.3.1
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ree

notifications:
  on_success: change
  on_failure: change
